#!/bin/bash
cd McSim/graphTraversal
make
cd ..
sudo bash -c "echo 0 > /proc/sys/kernel/yama/ptrace_scope"
make dbg INCS=-I/home/agy/mcsim/pin/extras/xed2-intel64/include -j 8 >> compiles.log
cd ../Pthread
make dbg TOOLS_DIR=/home/agy/mcsim/pin/source/tools
cd ..
#McSim/mcsim -mdfile ./Apps/md/md-o3-closed.py -runfile ./Apps/list/graph-traversal.py